/**
 * Mock job data for development and testing.
 * Dates are relative to now so date-range filters always have fresh data.
 */

import type { Job } from '@/types';

function daysAgo(days: number): string {
  return new Date(Date.now() - days * 24 * 60 * 60 * 1000).toISOString();
}

export const MOCK_JOBS: Job[] = [
  {
    id: 'mock-1',
    title: 'Senior Software Engineer',
    company: 'TechFlow Inc.',
    companyUrl: 'https://techflow.example.com',
    location: 'San Francisco, CA',
    postedAt: daysAgo(0),
    postedAtRelative: 'Today',
    url: 'https://linkedin.com/jobs/view/mock-1',
    description: 'We are looking for a Senior Software Engineer to join our growing platform team. You will design and build scalable distributed systems.',
    salary: '$180,000 - $220,000',
    employmentType: 'Full-time',
    experienceLevel: 'Senior',
    applicantCount: 42,
  },
  {
    id: 'mock-2',
    title: 'Product Manager',
    company: 'Nimbus AI',
    companyUrl: 'https://nimbus.example.com',
    location: 'New York, NY',
    postedAt: daysAgo(0),
    postedAtRelative: 'Today',
    url: 'https://linkedin.com/jobs/view/mock-2',
    description: 'Lead product strategy for our AI-powered analytics platform. Work closely with engineering and design to ship features that delight customers.',
    salary: '$160,000 - $200,000',
    employmentType: 'Full-time',
    experienceLevel: 'Mid-Senior',
    applicantCount: 87,
  },
  {
    id: 'mock-3',
    title: 'Junior Data Analyst',
    company: 'DataBridge Solutions',
    companyUrl: 'https://databridge.example.com',
    location: 'Austin, TX',
    postedAt: daysAgo(1),
    postedAtRelative: '1 day ago',
    url: 'https://linkedin.com/jobs/view/mock-3',
    description: 'Entry-level data analyst position. Work with SQL, Python, and BI tools to generate insights for our clients.',
    salary: '$65,000 - $80,000',
    employmentType: 'Full-time',
    experienceLevel: 'Entry',
    applicantCount: 156,
  },
  {
    id: 'mock-4',
    title: 'VP of Engineering',
    company: 'ScaleUp Corp',
    companyUrl: 'https://scaleup.example.com',
    location: 'Remote',
    postedAt: daysAgo(1),
    postedAtRelative: '1 day ago',
    url: 'https://linkedin.com/jobs/view/mock-4',
    description: 'Lead a team of 50+ engineers. Define technical vision and execution strategy for our Series C fintech startup.',
    salary: '$280,000 - $350,000',
    employmentType: 'Full-time',
    experienceLevel: 'Executive',
    applicantCount: 23,
  },
  {
    id: 'mock-5',
    title: 'DevOps Engineer',
    company: 'CloudNine Systems',
    companyUrl: 'https://cloudnine.example.com',
    location: 'Seattle, WA',
    postedAt: daysAgo(2),
    postedAtRelative: '2 days ago',
    url: 'https://linkedin.com/jobs/view/mock-5',
    description: 'Build and maintain CI/CD pipelines, Kubernetes clusters, and cloud infrastructure on AWS.',
    salary: '$140,000 - $175,000',
    employmentType: 'Full-time',
    experienceLevel: 'Mid',
    applicantCount: 64,
  },
  {
    id: 'mock-6',
    title: 'Marketing Coordinator',
    company: 'BrightPath Media',
    companyUrl: 'https://brightpath.example.com',
    location: 'Chicago, IL',
    postedAt: daysAgo(2),
    postedAtRelative: '2 days ago',
    url: 'https://linkedin.com/jobs/view/mock-6',
    description: 'Coordinate multi-channel marketing campaigns. Manage social media, email marketing, and content calendar.',
    salary: '$55,000 - $70,000',
    employmentType: 'Full-time',
    experienceLevel: 'Entry',
    applicantCount: 203,
  },
  {
    id: 'mock-7',
    title: 'Head of Sales',
    company: 'RevenuePilot',
    companyUrl: 'https://revenuepilot.example.com',
    location: 'Boston, MA',
    postedAt: daysAgo(3),
    postedAtRelative: '3 days ago',
    url: 'https://linkedin.com/jobs/view/mock-7',
    description: 'Build and lead a sales team from scratch. Define go-to-market strategy for our B2B SaaS platform.',
    salary: '$200,000 - $250,000 + commission',
    employmentType: 'Full-time',
    experienceLevel: 'Director',
    applicantCount: 31,
  },
  {
    id: 'mock-8',
    title: 'Full Stack Developer',
    company: 'PixelForge Studio',
    companyUrl: 'https://pixelforge.example.com',
    location: 'Los Angeles, CA',
    postedAt: daysAgo(3),
    postedAtRelative: '3 days ago',
    url: 'https://linkedin.com/jobs/view/mock-8',
    description: 'Build web applications using React, Node.js, and PostgreSQL. Small team, high impact.',
    salary: '$120,000 - $150,000',
    employmentType: 'Full-time',
    experienceLevel: 'Mid',
    applicantCount: 118,
  },
  {
    id: 'mock-9',
    title: 'UX Designer',
    company: 'DesignWave',
    companyUrl: 'https://designwave.example.com',
    location: 'Portland, OR',
    postedAt: daysAgo(5),
    postedAtRelative: '5 days ago',
    url: 'https://linkedin.com/jobs/view/mock-9',
    description: 'Design intuitive user experiences for enterprise B2B products. Conduct user research and create prototypes in Figma.',
    salary: '$110,000 - $140,000',
    employmentType: 'Full-time',
    experienceLevel: 'Senior',
    applicantCount: 76,
  },
  {
    id: 'mock-10',
    title: 'Chief Technology Officer',
    company: 'GreenLeaf Robotics',
    companyUrl: 'https://greenleaf.example.com',
    location: 'Denver, CO',
    postedAt: daysAgo(5),
    postedAtRelative: '5 days ago',
    url: 'https://linkedin.com/jobs/view/mock-10',
    description: 'Define technical strategy for our Series B robotics company. Lead R&D and engineering teams.',
    salary: '$300,000 - $400,000 + equity',
    employmentType: 'Full-time',
    experienceLevel: 'Executive',
    applicantCount: 12,
  },
  {
    id: 'mock-11',
    title: 'Backend Engineer',
    company: 'PayStream Financial',
    companyUrl: 'https://paystream.example.com',
    location: 'Miami, FL',
    postedAt: daysAgo(7),
    postedAtRelative: '1 week ago',
    url: 'https://linkedin.com/jobs/view/mock-11',
    description: 'Build payment processing microservices in Go. PCI compliance experience preferred.',
    salary: '$150,000 - $185,000',
    employmentType: 'Full-time',
    experienceLevel: 'Senior',
    applicantCount: 53,
  },
  {
    id: 'mock-12',
    title: 'Sales Development Representative',
    company: 'Outbound.io',
    companyUrl: 'https://outbound.example.com',
    location: 'Atlanta, GA',
    postedAt: daysAgo(7),
    postedAtRelative: '1 week ago',
    url: 'https://linkedin.com/jobs/view/mock-12',
    description: 'Generate qualified leads through cold outreach. Base salary plus uncapped commission.',
    salary: '$50,000 - $65,000 + commission',
    employmentType: 'Full-time',
    experienceLevel: 'Entry',
    applicantCount: 245,
  },
  {
    id: 'mock-13',
    title: 'Machine Learning Engineer',
    company: 'DeepSight Labs',
    companyUrl: 'https://deepsight.example.com',
    location: 'San Jose, CA',
    postedAt: daysAgo(10),
    postedAtRelative: '10 days ago',
    url: 'https://linkedin.com/jobs/view/mock-13',
    description: 'Train and deploy ML models for computer vision applications. PyTorch, CUDA, and cloud MLOps experience required.',
    salary: '$190,000 - $240,000',
    employmentType: 'Full-time',
    experienceLevel: 'Senior',
    applicantCount: 38,
  },
  {
    id: 'mock-14',
    title: 'Project Manager',
    company: 'BuildRight Construction',
    companyUrl: 'https://buildright.example.com',
    location: 'Dallas, TX',
    postedAt: daysAgo(10),
    postedAtRelative: '10 days ago',
    url: 'https://linkedin.com/jobs/view/mock-14',
    description: 'Manage commercial construction projects from planning to completion. PMP certification required.',
    salary: '$90,000 - $120,000',
    employmentType: 'Full-time',
    experienceLevel: 'Mid',
    applicantCount: 67,
  },
  {
    id: 'mock-15',
    title: 'Frontend Developer',
    company: 'Accenture',
    companyUrl: 'https://accenture.com',
    location: 'Washington, DC',
    postedAt: daysAgo(14),
    postedAtRelative: '2 weeks ago',
    url: 'https://linkedin.com/jobs/view/mock-15',
    description: 'Build React-based enterprise dashboards for government clients. Secret clearance preferred.',
    salary: '$130,000 - $160,000',
    employmentType: 'Full-time',
    experienceLevel: 'Mid',
    applicantCount: 92,
  },
  {
    id: 'mock-16',
    title: 'Customer Success Manager',
    company: 'SaaSify',
    companyUrl: 'https://saasify.example.com',
    location: 'Remote',
    postedAt: daysAgo(14),
    postedAtRelative: '2 weeks ago',
    url: 'https://linkedin.com/jobs/view/mock-16',
    description: 'Own a portfolio of enterprise accounts. Drive adoption, retention, and expansion revenue.',
    salary: '$100,000 - $130,000',
    employmentType: 'Full-time',
    experienceLevel: 'Mid',
    applicantCount: 134,
  },
  {
    id: 'mock-17',
    title: 'Security Engineer',
    company: 'CyberShield Inc.',
    companyUrl: 'https://cybershield.example.com',
    location: 'Remote',
    postedAt: daysAgo(20),
    postedAtRelative: '20 days ago',
    url: 'https://linkedin.com/jobs/view/mock-17',
    description: 'Perform penetration testing and vulnerability assessments. OSCP or equivalent certification required.',
    salary: '$145,000 - $180,000',
    employmentType: 'Full-time',
    experienceLevel: 'Senior',
    applicantCount: 29,
  },
  {
    id: 'mock-18',
    title: 'Intern - Software Engineering',
    company: 'Oracle',
    companyUrl: 'https://oracle.com',
    location: 'Redwood City, CA',
    postedAt: daysAgo(21),
    postedAtRelative: '3 weeks ago',
    url: 'https://linkedin.com/jobs/view/mock-18',
    description: 'Summer internship program. Work on real projects with mentorship from senior engineers.',
    salary: '$40/hour',
    employmentType: 'Internship',
    experienceLevel: 'Intern',
    applicantCount: 412,
  },
  {
    id: 'mock-19',
    title: 'Director of Product',
    company: 'Deloitte Digital',
    companyUrl: 'https://deloitte.com',
    location: 'New York, NY',
    postedAt: daysAgo(25),
    postedAtRelative: '25 days ago',
    url: 'https://linkedin.com/jobs/view/mock-19',
    description: 'Lead product strategy for digital transformation practice. Manage a team of 10 product managers.',
    salary: '$220,000 - $280,000',
    employmentType: 'Full-time',
    experienceLevel: 'Director',
    applicantCount: 45,
  },
  {
    id: 'mock-20',
    title: 'Solutions Architect',
    company: 'Vertex Cloud',
    companyUrl: 'https://vertex.example.com',
    location: 'Phoenix, AZ',
    postedAt: daysAgo(28),
    postedAtRelative: '4 weeks ago',
    url: 'https://linkedin.com/jobs/view/mock-20',
    description: 'Design cloud architecture solutions for enterprise clients. AWS or Azure certifications required.',
    salary: '$160,000 - $200,000',
    employmentType: 'Contract',
    experienceLevel: 'Senior',
    applicantCount: 58,
  },
];
